### PR TITLE
Add source files

### PR DESCRIPTION
**Pull request by wcandillon**

### CODE REVIEW

**Comment by fcavalieri** [comment]
@wcandillon  awesome :) How do you plan to keep them up to date?

**Comment by wcandillon** [comment]
When they will change, the contributor will commit them? What do you mean exactly?

**Comment by dknochen** [comment]
@wcandillon @fcavalieri I think we should merge this. Its hard to trace changes otherwise.

**Comment by wcandillon** [comment]
@dknochen Looks good. But did you look if circleci provides windows-type services or to use app veyor next to or as a replacement of circleci for this project?

**Pull request merged**
